#!/usr/bin/env python3
# data-licences.py - writes DATA_LICENSES.md, the per-file licence table for every DATA
# file in this repository, from the provenance records (the one source of truth).
#   python generation/data-licences.py            write DATA_LICENSES.md
#   python generation/data-licences.py --check    exit 1 if DATA_LICENSES.md is stale
# The repository's MIT licence (LICENSE) covers scripts and original code only; no data
# file is MIT. A dataset whose origin is unresolved is listed as UNLICENSED: no licence
# is granted for it by anyone here.
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "DATA_LICENSES.md")


def rows():
    out = []
    pdir = os.path.join(REPO, "provenance")
    for name in sorted(os.listdir(pdir)):
        if not name.endswith(".json"):
            continue
        r = json.load(open(os.path.join(pdir, name), encoding="utf-8"))
        f = r.get("file", "")
        where = ("packs/" + f) if f.endswith(".gz") else f
        status = r.get("verification", "VERIFIED")
        attribution = r.get("attribution", "")
        if status == "UNVERIFIED":
            attribution = "-"
        out.append((where, r.get("licence", ""), status, attribution, "provenance/" + name))
    # candidates/: unpublished candidate packs (generation/build-candidates.py), each with
    # its record beside it - data like any other, so listed with its licence
    cdir = os.path.join(REPO, "candidates")
    if os.path.isdir(cdir):
        for name in sorted(os.listdir(cdir)):
            if not name.endswith(".json"):
                continue
            r = json.load(open(os.path.join(cdir, name), encoding="utf-8"))
            out.append(("candidates/" + r["file"], r["licence"], "CANDIDATE (unpublished)",
                        r.get("attribution", ""), "candidates/" + name))
    return out


def render():
    lines = [
        "# Data licences",
        "",
        "Generated by `generation/data-licences.py` from `provenance/` - do not edit by hand.",
        "",
        "**The repository's MIT licence (`LICENSE`) covers its scripts and original code only.**",
        "No word list, corpus, pack, held-out test sample or other generated data is MIT. Each",
        "data file keeps the licence of the source it was derived from, below; the full",
        "notices are in `licences/`. Files marked **UNLICENSED** are historical datasets whose",
        "origin was never recorded: no licence is granted for them by anyone here, and they",
        "must not be given new uses until their origin is resolved or they are replaced.",
        "",
        "Derived files follow their source: the held-out test samples (`generation/*_ngrams_test*.tsv`)",
        "and build records (`generation/builds/`) are derived from Tatoeba sentences and are",
        "CC BY 2.0 FR with the Tatoeba attribution.",
        "",
        "| file | licence | status | attribution | record |",
        "|---|---|---|---|---|",
    ]
    for where, lic, status, att, rec in rows():
        lines.append("| `%s` | %s | %s | %s | `%s` |" % (where, lic, status, att.replace("|", "/"), rec))
    return "\n".join(lines) + "\n"


def main():
    text = render()
    if "--check" in sys.argv:
        cur = open(OUT, encoding="utf-8").read().replace("\r\n", "\n") if os.path.isfile(OUT) else ""
        if cur != text:
            print("FAIL DATA_LICENSES.md is stale - run python generation/data-licences.py")
            return 1
        print("DATA_LICENSES.md up to date")
        return 0
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote DATA_LICENSES.md (%d files)" % len(rows()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
